# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b66d235aa388ab8ca0c53919b39180e9a074b4b470b1cdfba07c434b1f77309cef79931baba967c8008ad513927b073edfb636ba5a71843f74536f82ae2c288

test:
  secret_key_base: 10fae128f21b8ae2260afae68784f63447b0417d3b232a30a7ccd6fdf1defc7d3e0c2736f70e44f6bf41737709a0f902651d1ffade35667572b3da3a616fbda6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
