class Lorem < ApplicationRecord

  def bacon
    "Brisket hamburger pancetta bacon flank alcatra shank salami sirloin. Short ribs ham hock fatback tail, andouille kevin salami prosciutto kielbasa burgdoggen. Strip steak ribeye hamburger, leberkas short loin kielbasa meatball chicken t-bone short ribs tri-tip tail corned beef drumstick tenderloin. Prosciutto filet mignon porchetta beef tenderloin. Pancetta shank landjaeger venison flank tongue turkey pork. Pork belly tongue ribeye jowl kielbasa pig venison corned beef short ribs meatball pancetta t-bone shankle shoulder. Pig chuck ground round cupim, ham hock biltong brisket kevin boudin tenderloin short ribs drumstick flank.
    Strip steak spare ribs shankle pork loin pork flank short loin. Drumstick pancetta turkey corned beef strip steak short loin andouille chuck jowl cupim picanha bresaola. Sirloin flank venison beef cupim, bresaola bacon doner boudin. Leberkas tenderloin ham, alcatra doner pancetta beef ribs. Ham capicola hamburger shankle fatback frankfurter landjaeger t-bone shank pig flank tenderloin kielbasa. Jerky flank ground round, leberkas t-bone chuck kielbasa venison.
    Pork belly flank prosciutto frankfurter, biltong meatloaf swine boudin brisket ribeye cow tenderloin tail kevin bacon. Rump chicken swine doner fatback ball tip capicola flank pork boudin tail meatball. Swine cow strip steak burgdoggen picanha meatloaf pork chop tri-tip jowl salami tenderloin bresaola, andouille frankfurter. Venison alcatra short loin prosciutto strip steak. Short ribs pork belly prosciutto, jerky shankle biltong picanha meatloaf doner pig. Sirloin chicken cow chuck short loin.
    Venison pastrami kielbasa shank. Swine kevin pork chop kielbasa. Short ribs sausage venison short loin, beef bresaola hamburger landjaeger jowl strip steak ham. Pork ground round tri-tip frankfurter meatball. Short loin turkey shoulder, meatball corned beef shank capicola chicken. Short loin t-bone tri-tip pancetta venison tenderloin biltong hamburger bresaola beef bacon. Kielbasa short ribs shankle doner."
  end

  def zombie
    "Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.
    Cum horribilem walking dead resurgere de crazed sepulcris creaturis, zombie sicut de grave feeding iride et serpens. Pestilentia, shaun ofthe dead scythe animated corpses ipsa screams. Pestilentia est plague haec decaying ambulabat mortuos. Sicut zeder apathetic malus voodoo. Aenean a dolor plan et terror soulless vulnerum contagium accedunt, mortui iam vivam unlife. Qui tardius moveri, brid eof reanimator sed in magna copia sint terribiles undeath legionis. Alii missing oculis aliorum sicut serpere crabs nostram. Putridi braindead odores kill and infect, aere implent left four dead.
    Lucio fulci tremor est dark vivos magna. Expansis creepy arm yof darkness ulnis witchcraft missing carnem armis Kirkman Moore and Adlard caeruleum in locis. Romero morbo Congress amarus in auras. Nihil horum sagittis tincidunt, zombie slack-jawed gelida survival portenta. The unleashed virus est, et iam zombie mortui ambulabunt super terram. Souless mortuum glassy-eyed oculos attonitos indifferent back zom bieapoc alypse. An hoc dead snow braaaiiiins sociopathic incipere Clairvius Narcisse, an ante? Is bello mundi z?
    In Craven omni memoria patriae zombieland clairvius narcisse religionis sunt diri undead historiarum. Golums, zombies unrelenting et Raimi fascinati beheading. Maleficia! Vel cemetery man a modern bursting eyeballs perhsaps morbi. A terrenti flesh contagium. Forsitan deadgurl illud corpse Apocalypsi, vel staggering malum zomby poenae chainsaw zombi horrifying fecimus burial ground. Indeflexus shotgun coup de poudre monstra per plateas currere. Fit de decay nostra carne undead. Poenitentiam violent zom biehig hway agite RE:dead pœnitentiam! Vivens mortua sunt apud nos night of the living dead."
  end

  def cheese
    "Fromage frais cheesy feet when the cheese comes out everybody's happy. Feta cheese on toast cheesy feet cheese on toast queso dolcelatte who moved my cheese cheese slices. Boursin the big cheese bavarian bergkase fondue squirty cheese pecorino rubber cheese pecorino. Red leicester cheesy feet.
    Who moved my cheese halloumi stinking bishop. Stilton cream cheese ricotta chalk and cheese hard cheese monterey jack roquefort jarlsberg. Ricotta cheese slices squirty cheese brie when the cheese comes out everybody's happy when the cheese comes out everybody's happy the big cheese cheese and wine. Mozzarella emmental bocconcini fromage fondue.
    Taleggio cheesy feet fromage frais. Goat halloumi swiss cheese and biscuits dolcelatte cheeseburger cheesecake mascarpone. Babybel cheese strings stilton cow croque monsieur cheesy grin macaroni cheese red leicester. Cut the cheese pecorino squirty cheese cheese triangles cheese triangles danish fontina ricotta.
    Red leicester manchego jarlsberg. Everyone loves cheddar macaroni cheese babybel danish fontina blue castello squirty cheese cheese on toast. Cow caerphilly manchego croque monsieur goat fromage manchego rubber cheese. Stilton stilton bocconcini cut the cheese parmesan gouda rubber cheese paneer. Cheesecake cheese on toast cheese triangles."
  end
end
